repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: local
  # switched to local to have it run with synced dependencies in the venv
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        args: [--config-file=pyproject.toml, src/]
        pass_filenames: false
        # note that this will always run on all files, regardless of the --all-files flag, because mypy needs to see all files to work correctly in case a type change in one file affects the types in another file. 